services:
  order-service:
    container_name: order-service
    build:
      context: ./
      dockerfile: ./services/order-service/Dockerfile
      args:
        - NODE_ENV=development
    restart: always
    environment:
      - NODE_ENV=development
    ports:
      - 3001:3001
      - 9229:9229
    networks:
      - ts_stack_network
    healthcheck:
      disable: true
    command: npx nodemon --inspect=0.0.0.0:9229 --signal SIGINT --nolazy .dist/index.js
networks:
  ts_stack_network:
    external: true
volumes:
  notused:
